AppointmentScheduler/AppointmentScheduler/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppointmentScheduler.Controllers
{
  public class AdminController : Controller
  {
    public ActionResult AppointmentInfo()
    {
      return View();
    }

    public ActionResult Cancel()
    {
      return View();
    }

    public ActionResult EditAppointment()
    {
      return View();
    }

    public ActionResult EditBranch()
    {
      return View();
    }

    public ActionResult Index()
    {
      return View();
    }

    public ActionResult Reports()
    {
      return View();
    }

    public ActionResult Search()
    {
      return View();
    }
  }
}

AppointmentScheduler/AppointmentScheduler/Views/Admin/AppointmentInfo.cshtml
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="header-banner-wrapper">
  <div class="adminMainContent">




    <div>
      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
        <span>Search Appointments</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
        <span>Reports</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
        <span>Branch Info</span>
      </a>

    </div>


    <h2>Appointment Details</h2>

    <p>
      Name:
    </p>

    <p>
      Phone:
    </p>

    <p>
      Email:
    </p>

    <p>
      Date:
    </p>

    <p>
      Time:
    </p>

    <p>
      Appointment Type:
    </p>

    <p>
      Confirmation#:
    </p>

    <p>
      Notes:
    </p>


    <!--link buttons-->
    <a class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
      <span>Edit/Reschedule</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Cancel", "Admin")">
      <span>Cancel</span>
    </a>





  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Admin/Cancel.cshtml
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="header-banner-wrapper">
  <div class="adminMainContent">


    <div>
      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
        <span>Search Appointments</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
        <span>Reports</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
        <span>Branch Info</span>
      </a>

    </div>

    <h2>Appointment Lookup</h2>

    <p>
      Are you sure you want to cancel this appointment?
    </p>

    <a class="btn submit custbtn" href="@Url.Action("AppointmentInfo", "Admin")">
      <span>Yes</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("AppointmentInfo", "Admin")">
      <span>No</span>
    </a>




  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Admin/EditAppointment.cshtml
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="header-banner-wrapper">
  <div class="adminMainContent">




    <div>
      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
        <span>Search Appointments</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
        <span>Reports</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
        <span>Branch Info</span>
      </a>

    </div>

    <h2>Appointment Details</h2>

    <p>
      Name:<input />
    </p>

    <p>
      Phone:<input />
    </p>

    <p>
      Email:<input />
    </p>

    <p>
      Date:<input />
    </p>

    <p>
      Time:<input />
    </p>

    <p>
      Appointment Type:
      <select id="ctlQuestions" tabindex="11">
        <option value="">Select Reason</option>
        <option value="Checking">Checking</option>
        <option value="Savings">Savings</option>
        <option value="IRA">IRA</option>
        <option value="Loans">Loans</option>
        <option value="Other">Other</option>
      </select>
    </p>

    <p>
      Notes:<input />
    </p>


    <a class="btn submit custbtn" href="@Url.Action("AppointmentInfo", "Admin")">
      <span>Back</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("AppointmentInfo", "Admin")">
      <span>Submit Changes</span>
    </a>




  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Admin/EditBranch.cshtml
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="header-banner-wrapper">
  <div class="adminMainContent">



    <div>
      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
        <span>Search Appointments</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
        <span>Reports</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
        <span>Branch Info</span>
      </a>

    </div>

      <p>Branch ON/OFF: <input type="radio" /> </p>
      <!--
      <input type="checkbox" data-role="flipswitch" name="switch" id="switch" data-wrapper-class="custom-size-flipswitch">
      -->

      <p>Days:</p>

      <p>Times:</p>

      <p>
        <strong>Appointment Types:</strong><br>
        Checking & Savings <input type="checkbox" name="CheckingSavings" value="ON" /> <br>
        Mortgage <input type="checkbox" name="Mortgage" value="ON" /> <br>
        Loans <input type="checkbox" name="Loans" value="ON" /> <br>
        Other <input type="checkbox" name="Other" value="ON" />
      </p>


      <p><strong>Contact Info:</strong><br>Phone Number:<input /></p>


      <a class="btn submit custbtn" href="#">
        <span>Save Changes</span>
      </a>




    </div>
  </div>

AppointmentScheduler/AppointmentScheduler/Views/Admin/Index.cshtml
@using System.Web.UI.WebControls
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<a class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
  <span>Search <br> Appointments</span>
</a>

<a class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
  <span>Reports</span>
</a>

<a class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
  <span>Branch Info</span>
</a>

AppointmentScheduler/AppointmentScheduler/Views/Admin/Reports.cshtml
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="header-banner-wrapper">
  <div class="adminMainContent">


    <div>
      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
        <span>Search Appointments</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
        <span>Reports</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
        <span>Branch Info</span>
      </a>

    </div>

    <div>
      <p>First Name:<input /></p>

      <p>Last Name:<input /></p>

      <p>Confirmation#:<input /></p>

      <p>Email:<input /></p>


      <p>Date:<input /></p>

      <p>Branch:<input /></p>

      <p>Type:<input /></p>

    </div>

    <a class="btn submit custbtn" href="#">
      <span>Run Report</span>
    </a>



  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Admin/Search.cshtml
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="header-banner-wrapper">
  <div class="adminMainContent">



    <div>
      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Search", "Admin")">
        <span>Search Appointments</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("Reports", "Admin")">
        <span>Reports</span>
      </a>

      <a id="topBtn" class="btn submit custbtn" href="@Url.Action("EditBranch", "Admin")">
        <span>Branch Info</span>
      </a>

    </div>

    <h1 class='text-center'>Search Appointments</h1>

    <div class='text-center'>
      <p>
        First Name:
        <input />
      </p>

      <p>
        Last Name:
        <input />
      </p>

      <p>
        Email:
        <input />
      </p>

      <p>OR</p>

      <p>
        Confirmation #:
        <input />
      </p>
    </div>


    <a class="btn submit custbtn" href="@Url.Action("AppointmentInfo", "Admin")">
      <span>Search</span>
    </a>


  </div>
</div>