AppointmentScheduler/AppointmentScheduler/Controllers/LookupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppointmentScheduler.Controllers
{
  public class LookupController : Controller
  {
    // GET: Lookup
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult Lookup()
    {
      return View();
    }

    public ActionResult Change()
    {
      return View();
    }

    public ActionResult Cancel()
    {
      return View();
    }

    public ActionResult Details()
    {
      return View();
    }

    public ActionResult Reschedule()
    {
      return View();
    }

    public ActionResult Confirmation()
    {
      return View();
    }

    public ActionResult CancelConfirmation()
    {
      return View();
    }
  }
}

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Cancel.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">
    <h1>Cancel Appointment</h1>

    <h2></h2>

    <p>
      Are you sure you want to cancel your appointment?
    </p>

    <a class="btn submit custbtn" href="@Url.Action("CancelConfirmation", "Lookup")">
      <span>Yes</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Details", "Lookup")">
      <span>No</span>
    </a>

  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/CancelConfirmation.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">

    <h1>Cancel Appointment</h1>

    <h2>We're sorry to see you go!</h2>

    <p>
      Your appointment has been canceled.
      <br>
      An email confirmation has been sent to you.
    </p>

    <a class="btn submit custbtn" href="@Url.Action("Index", "Home")">
      <span>Menu</span>
    </a>

  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Change.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">
    <h1>Change Appointment Details</h1>

    <h2></h2>

    <p>
      Name:<input />
    </p>

    <p>
      Phone:<input />
    </p>

    <p>
      Email:<input />
    </p>

    <p>
      Date:<input />
    </p>

    <p>
      Time:<input />
    </p>

    <p>
      Appointment Type:
      <select class="form-control">
        <option value="one">Select Reason</option>
        <option value="two">Checking</option>
        <option value="three">Savings</option>
        <option value="four">IRA</option>
        <option value="five">Loans</option>
      </select>
    </p>

    <p>
      Notes:<input />
    </p>

    <a class="btn submit custbtn" href="@Url.Action("Details", "Lookup")">
      <span>Back</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Confirmation", "Lookup")">
      <span>Submit</span>
    </a>

  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Confirmation.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">
    <h1>Appointment Updated</h1>
    <h2>Thank you!</h2>
    <p>
      Your appointment has been updated.
      <br>
      An email confirmation has been sent to you.
    </p>

    <p>
      Confirmation #:
    </p>

    <p>
      What to bring with you:
    </p>


    <a class="btn submit custbtn" href="@Url.Action("Index", "Home")">
      <span>Menu</span>
    </a>

    <a class="btn submit custbtn" href="javascript:window.print()">
      <span>Print</span>
    </a>

  </div>

















</div>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Details.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">
    <h1>Appointment Details</h1>

    <h2></h2>

    <p>
      Name:
    </p>

    <p>
      Phone:
    </p>

    <p>
      Email:
    </p>

    <p>
      Date:
    </p>

    <p>
      Time:
    </p>

    <p>
      Appointment Type:
    </p>

    <p>
      Confirmation#:
    </p>

    <p>
      Notes:
    </p>

    <a class="btn submit custbtn" href="@Url.Action("Change", "Lookup")">
      <span>Edit</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Rechedule", "Lookup")">
      <span>Reschedule</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Cancel", "Lookup")">
      <span>Cancel</span>
    </a>

  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Index.cshtml
@model dynamic

@{
  Layout = null;
}

<!DOCTYPE html>

<html>
  <head>
    <title>title</title>
  </head>
  <body>
    <div>
        
    </div>
  </body>
</html>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Lookup.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">
    <h1>Lookup Appointment</h1>

    <h2></h2>

    <p>
      First Name:
      <input id="fName" />
    </p>

    <p>
      Last Name:
      <input id="lName" />
    </p>

    <p>
      Email:
      <input id="email" />
    </p>


    <a class="btn submit custbtn" href="@Url.Action("Index", "Home")">
      <span>Back</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Details", "Lookup")">
      <span>Lookup</span>
    </a>

  </div>
</div>

AppointmentScheduler/AppointmentScheduler/Views/Lookup/Reschedule.cshtml
@using System.Web.Razor.Parser.SyntaxTree
@{
  ViewBag.Title = "Home Page";
}

<div class="header-banner-wrapper">
  <div class="content">
    <h1>Reschedule</h1>
    <h2></h2>
    <p>

    </p>

    <a class="btn submit custbtn" href="@Url.Action("Details", "Lookup")">
      <span>Back</span>
    </a>

    <a class="btn submit custbtn" href="@Url.Action("Confirmation", "Lookup")">
      <span>Submit</span>
    </a>

  </div>
</div>